[package]

name = "rustfft"
version = "3.0.1"
authors = ["Allen Welkie <allen.welkie at gmail>", "Elliott Mahler <join.together at gmail>"]

description = "Compute FFTs of any size in O(nlogn) time, in pure Rust."
documentation = "https://docs.rs/rustfft/"
repository = "https://github.com/awelkie/RustFFT"
keywords = ["fft", "dft", "discrete", "fourier", "transform"]
categories = ["algorithms", "compression", "multimedia::encoding", "science"]
license = "MIT OR Apache-2.0"

[dependencies]
num-complex = "0.3"
num-integer = "0.1.43"
num-traits = "0.2"
strength_reduce = "^0.2.1"
transpose = "0.2"

[dev-dependencies]
rand = "0.5"
